version: '3.4'

services:
  mscatalogdb:
    image: mongo

  msbasketdb:
    image: redis:alpine

  msdiscountdb:
    image: postgres

  msorderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  msrabbitmq:
    image: rabbitmq:3-management-alpine




  msportainer:
    image: portainer/portainer-ce

  mscatalogapi:
    image: ${DOCKER_REGISTRY-}mscatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  msbasketapi:
    image: ${DOCKER_REGISTRY-}msbasketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  msdiscountdbui:
    image: dpage/pgadmin4

  msdiscountapi:
    image: ${DOCKER_REGISTRY-}msdiscountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  msdiscountgrpc:
    image: ${DOCKER_REGISTRY-}msdiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  msorderapi:
    image: ${DOCKER_REGISTRY-}msorderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile

  msapigw:
    image: ${DOCKER_REGISTRY-}msapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

  msshoppingaggregator:
    image: ${DOCKER_REGISTRY-}msshoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:




