version: '3.4'

services:
  mscatalogdb:
    container_name: mscatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  msbasketdb:
    container_name: msbasketdb
    restart: always
    ports:
      - "6379:6379"

  msdiscountdb:
    container_name: msdiscountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  msorderdb:
    container_name: msorderdb
    environment:
      SA_PASSWORD: SwN12345678
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  msrabbitmq:
    container_name: msrabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"



  msportainer:
    container_name: msportainer
    restart: always
    ports:
      - "8090:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mscatalogapi:
    container_name: mscatalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mscatalogdb:27017"
    depends_on:
      - mscatalogdb
    ports:
      - "8000:80"

  msbasketapi:
    container_name: msbasketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=msbasketdb:6379"
      - "GrpcSettings:DiscountUrl=http://msdiscountgrpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@msrabbitmq:5672"
    depends_on:
      - msbasketdb
      - msrabbitmq
    ports:
      - "8001:80"

  msdiscountdbui:
    container_name: msdiscountdbui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  msdiscountapi:
    container_name: msdiscountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=msdiscountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - msdiscountdb
    ports:
      - "8002:80"

  msdiscountgrpc:
    container_name: msdiscountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=msdiscountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - msdiscountdb
    ports:
      - "8003:80"

  msorderapi:
    container_name: msorderapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnectionString=Server=msorderdb;Database=OrderDb;User Id=sa;Password=SwN12345678"
      - "EventBusSettings:HostAddress=amqp://guest:guest@msrabbitmq:5672"
    depends_on:
      - msorderdb
      - msrabbitmq
    ports:
      - "8004:80"

