version: '3.4'

services:
  mscatalogdb:
    container_name: mscatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  msbasketdb:
    container_name: msbasketdb
    restart: always
    ports:
      - "6379:6379"

  msdiscountdb:
    container_name: msdiscountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  msdiscountdbui:
    container_name: msdiscountdbui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin




  msportainer:
    container_name: msportainer
    restart: always
    ports:
      - "8090:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mscatalogapi:
    container_name: mscatalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mscatalogdb:27017"
    depends_on:
      - mscatalogdb
    ports:
      - "8000:80"

  msbasketapi:
    container_name: msbasketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=msbasketdb:6379"
    depends_on:
      - msbasketdb
    ports:
      - "8001:80"

  msdiscountapi:
    container_name: msdiscountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Mehmet=Deneme
      - "DatabaseSettings:ConnectionString=Server=msdiscountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - msdiscountdb
    ports:
      - "8002:80"

