version: '3.4'

services:
  mscatalogdb:
    image: mongo

  msbasketdb:
    image: redis:alpine

  msportainer:
    image: portainer/portainer-ce

  mscatalogapi:
    image: ${DOCKER_REGISTRY-}mscatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  msbasketapi:
    image: ${DOCKER_REGISTRY-}msbasketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
